# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs
          retention-days: 7

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports
          retention-days: 7
